name: send_message
description: "Action que envia un telegram"
inputs:
  telegram_token:
    description: "token de telegram"
    required: false
  telegram_chat:
    description: "chat id de telegram"
    required: false
runs:
  using: "node16"
  main: "dist/index.js"