name: primer-ejemplo
on: 
  push:
   branches:
    - nodejs_linter_job
jobs:
  linter-execution:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: github/super-linter@v3
    env:
      - DEFAULT_BRANCH: nodejs_example
      - GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - LINTER_RULES_PATH: /
      - JAVASCRIPT_ES_CONFIG_FILE: .eslintrc.json
      - VALIDATE_JAVASCRIPT_ES: true