name: primer-ejemplo
on: 
  push:
   branches:
    - github_action_readme
jobs:
  test-execution:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: install
        run: npm install -D
      - name: jest test
        id: test
        run: npm install jest && npm test
        # continue-on-error: true
      - name: Check on failures
        if: steps.test.outcome != 'success'
        run: echo "error"

  readme:
    needs: test-execution
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: action meme
        uses: ./.github/actions/changereadme
        env:
          frase_positiva: "tenguy/Olee_funcionan_los_Tests"
          frase_negativa: "cryingfloor/Fallaron_los_Tests"
          resultado_tests: ${{ needs.test-execution.result }}
      - name: Endbug
        uses: EndBug/add-and-commit@v9
        with:
          add: "."
          author_name: "Santi Martinez Albert"
          author_email: "santimartinezalbert02@gmail.com"
          message: "Readme Updated succesfully"
          push: true
