name: primer-ejemplo
on: 
  push:
   branches:
    - nodejs_environment_job
jobs:
  linter-execution:
    strategy:
      matrix:
        node: [10,12]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setting node version
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - name: Linter execution
        uses: github/super-linter@v4.9.7
        env:
          DEFAULT_BRANCH: nodejs_example
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LINTER_RULES_PATH: /
          JAVASCRIPT_ES_CONFIG_FILE: .eslintrc.json
          VALIDATE_JAVASCRIPT_ES: true
  test-execution:
    needs: linter-execution
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: jest test
        run: npm install jest && npm test
  environment_test_execution:
    strategy:
      matrix:
        include:
          - DESTINATION_PERSON: 2DAW
    needs: [linter-execution, test-execution]
    runs-on: ubuntu-latest
    steps:
      - name: hola
        uses: adeloyedeji/github-actions-hello@v1.0
        with: 
          who-to-greet: ${{matrix.DESTINATION_PERSON}}
  send-mail:
    runs-on: ubuntu-latest
    steps:
      - name: Send mail
        run: echo ${{secrets.GITHUB_EMAIL}}
        # uses: dawidd6/action-send-mail@v3
        # with:
        #   server_address: smtp.gmail.com
        #   server_port: 465
        #   username: ${{secrets.GITHUB_EMAIL}}
        #   password: ${{secrets.GITHUB_PASSWORD}}
        #   from: Santi Martinez
        #   to: santimartinezalbert02@gmail.com
        #   subject: Test
        #   body: Error en el test