name: primer-ejemplo
on: 
  push:
   branches:
    - github_action_readme
jobs:
  test-execution:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: install
        run: npm install -D
      - name: jest test
        id: test
        run: npm test
        continue-on-error: true
      - name: Check on failures
        if: steps.test.outcome != 'success'
        run: echo "error"

  readme:
    needs: test-execution
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: action meme
        uses: ./.github/actions/changereadme
        env:
          frase_positiva: "cryingfloor/Olee funcionan los Tests"
          frase_negativa: "cryingfloor/Fallaron los Tests"
          resultado_tests: ${{ needs.jest.result }}
