name: primer-ejemplo
on: 
  push:
   branches:
    - nodejs_nodeversions_job
jobs:
  linter-execution:
    matrix:
      os: ubuntu-latest
      node: [10,12]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: 
        uses: actions/setup-node@v2
          with:
            node-version: ${{ matrix.node }}
      - name: Linter execution
        uses: github/super-linter@v4.9.7
        env:
          DEFAULT_BRANCH: nodejs_example
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LINTER_RULES_PATH: /
          JAVASCRIPT_ES_CONFIG_FILE: .eslintrc.json
          VALIDATE_JAVASCRIPT_ES: true
  test-execution:
    needs: linter-execution
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: jest test
        run: npm install jest && npm test

